# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class FindUsersPayload(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            traits = schemas.DictSchema
            metadataPublic = schemas.DictSchema
            metadataAdmin = schemas.DictSchema
            __annotations__ = {
                "traits": traits,
                "metadataPublic": metadataPublic,
                "metadataAdmin": metadataAdmin,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traits"]) -> MetaOapg.properties.traits: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadataPublic"]) -> MetaOapg.properties.metadataPublic: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadataAdmin"]) -> MetaOapg.properties.metadataAdmin: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["traits", "metadataPublic", "metadataAdmin", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traits"]) -> typing.Union[MetaOapg.properties.traits, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadataPublic"]) -> typing.Union[MetaOapg.properties.metadataPublic, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadataAdmin"]) -> typing.Union[MetaOapg.properties.metadataAdmin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["traits", "metadataPublic", "metadataAdmin", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        traits: typing.Union[MetaOapg.properties.traits, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        metadataPublic: typing.Union[MetaOapg.properties.metadataPublic, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        metadataAdmin: typing.Union[MetaOapg.properties.metadataAdmin, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FindUsersPayload':
        return super().__new__(
            cls,
            *_args,
            traits=traits,
            metadataPublic=metadataPublic,
            metadataAdmin=metadataAdmin,
            _configuration=_configuration,
            **kwargs,
        )
