# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.activity_measurement.post import CreateActivityData
from openapi_client.paths.activity.get import QueryActivityData


class ActivityApi(
    CreateActivityData,
    QueryActivityData,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
