# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.entities.post import CreateEntity
from openapi_client.paths.entities_entity_id.delete import DeleteEntity
from openapi_client.paths.entities_entity_id.get import GetEntity
from openapi_client.paths.entities.get import ListEntities
from openapi_client.paths.entities_entity_id.patch import PatchEntity
from openapi_client.paths.entities_entity_id.put import UpdateEntity


class EntitiesApi(
    CreateEntity,
    DeleteEntity,
    GetEntity,
    ListEntities,
    PatchEntity,
    UpdateEntity,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
