# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.entities_entity_id_connections.post import CreateEntityConnection
from openapi_client.paths.entities_entity_id_connections_connection_id.delete import DeleteEntityConnection
from openapi_client.paths.entities_entity_id_connections_connection_id.get import GetEntityConnection
from openapi_client.paths.entities_entity_id_connections.get import ListEntityConnections
from openapi_client.paths.entities_entity_id_connections_connection_id.patch import PatchEntityConnection


class EntityConnectionsApi(
    CreateEntityConnection,
    DeleteEntityConnection,
    GetEntityConnection,
    ListEntityConnections,
    PatchEntityConnection,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
