# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.graph_entities.post import CreateV2Entity
from openapi_client.paths.graph_entities_entity_id.delete import DeleteV2Entity
from openapi_client.paths.graph_entities_entity_id.get import GetV2Entity
from openapi_client.paths.graph_entities.get import ListV2Entities
from openapi_client.paths.graph_entities_entity_id.patch import PatchV2Entity
from openapi_client.paths.graph_entities_entity_id.put import UpdateV2Entity


class EntitiesV2Api(
    CreateV2Entity,
    DeleteV2Entity,
    GetV2Entity,
    ListV2Entities,
    PatchV2Entity,
    UpdateV2Entity,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
