# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.modules.post import CreateModules
from openapi_client.paths.modules_module_id.delete import DeleteModule
from openapi_client.paths.modules.get import ListModules
from openapi_client.paths.modules_module_id.patch import PatchModule


class ModulesApi(
    CreateModules,
    DeleteModule,
    ListModules,
    PatchModule,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
