# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.permissions_check.post import CheckPermission
from openapi_client.paths.permissions.put import CreatePermission
from openapi_client.paths.permissions.delete import DeletePermission
from openapi_client.paths.permissions.get import ListPermissions
from openapi_client.paths.permissions.patch import PatchPermission


class PermissionsApi(
    CheckPermission,
    CreatePermission,
    DeletePermission,
    ListPermissions,
    PatchPermission,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
