# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.points.post import CreateEntityHistoricalData
from openapi_client.paths.points_query.post import QueryHistoricalEntityData


class PointsApi(
    CreateEntityHistoricalData,
    QueryHistoricalEntityData,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
