# coding: utf-8

"""
    Thingspine

    This page contains the documentation on how to use Thingspine services through HTTP API.   # noqa: E501

    The version of the OpenAPI document: 0.24.6
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.records_service.post import CreateRecord
from openapi_client.paths.records_service_record_id.delete import DeleteRecord
from openapi_client.paths.records_service.delete import DeleteRecords
from openapi_client.paths.records_service_record_id.get import GetRecord
from openapi_client.paths.records_service.get import ListRecords
from openapi_client.paths.records_service_record_id.patch import PatchRecord
from openapi_client.paths.records_service.patch import PatchRecords
from openapi_client.paths.records_service_record_id.put import UpdateRecord
from openapi_client.paths.records_service.put import UpdateRecords


class RecordsApi(
    CreateRecord,
    DeleteRecord,
    DeleteRecords,
    GetRecord,
    ListRecords,
    PatchRecord,
    PatchRecords,
    UpdateRecord,
    UpdateRecords,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
